import type { AppConfig, ThemeName } from '../types/providers'

export const themeNames: ThemeName[] = ['aurora', 'sakura', 'cyber', 'mint']

export const defaultConfig: AppConfig = {
  activeImageProviderId: 'custom-image',
  activeTextProviderId: 'openai-text',
  theme: 'aurora',
  imageProviders: [
    {
      id: 'openai-image',
      name: 'OpenAI Images',
      kind: 'openai',
      role: 'image',
      enabled: true,
      baseUrl: 'https://api.openai.com/v1',
      apiKey: '',
      model: 'gpt-image-1',
      textToImagePath: '/images/generations',
      imageToImagePath: '/images/edits',
      videoPath: '/videos',
      responsePath: 'data.0.b64_json',
    },
    {
      id: 'siliconflow-image',
      name: 'SiliconFlow',
      kind: 'siliconflow',
      role: 'image',
      enabled: true,
      baseUrl: 'https://api.siliconflow.cn/v1',
      apiKey: '',
      model: 'Kwai-Kolors/Kolors',
      textToImagePath: '/images/generations',
      imageToImagePath: '/images/edits',
      videoPath: '/videos/generations',
      responsePath: 'images.0.url',
    },
    {
      id: 'qwen-image',
      name: 'Qwen Image',
      kind: 'qwen',
      role: 'image',
      enabled: true,
      baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      apiKey: '',
      model: 'qwen-image',
      textToImagePath: '/images/generations',
      imageToImagePath: '/images/edits',
      videoPath: '/videos/generations',
      responsePath: 'data.0.url',
    },
    {
      id: 'novai-image',
      name: 'NovAI',
      kind: 'novai',
      role: 'image',
      enabled: true,
      baseUrl: 'https://api.novita.ai/v3/openai',
      apiKey: '',
      model: 'sd_xl_base_1.0',
      textToImagePath: '/images/generations',
      imageToImagePath: '/images/edits',
      videoPath: '/videos/generations',
      responsePath: 'data.0.url',
    },
    {
      id: 'custom-image',
      name: 'Local GPT Image Service',
      kind: 'custom',
      role: 'image',
      enabled: true,
      baseUrl:
        import.meta.env.VITE_DEFAULT_IMAGE_BASE_URL ??
        'http://192.168.0.117:8080/v1',
      apiKey: import.meta.env.VITE_DEFAULT_IMAGE_API_KEY ?? '',
      model: import.meta.env.VITE_DEFAULT_IMAGE_MODEL ?? 'gpt-image-2',
      textToImagePath: '/images/generations',
      imageToImagePath: '/images/edits',
      videoPath: '/videos/generations',
      responsePath: 'data.0.b64_json',
    },
  ],
  textProviders: [
    {
      id: 'openai-text',
      name: 'OpenAI Text',
      kind: 'openai',
      role: 'text',
      enabled: true,
      baseUrl: 'https://api.openai.com/v1',
      apiKey: '',
      model: 'gpt-4.1-mini',
      chatPath: '/chat/completions',
      responsePath: 'choices.0.message.content',
    },
    {
      id: 'siliconflow-text',
      name: 'SiliconFlow Text',
      kind: 'siliconflow',
      role: 'text',
      enabled: true,
      baseUrl: 'https://api.siliconflow.cn/v1',
      apiKey: '',
      model: 'Qwen/Qwen2.5-7B-Instruct',
      chatPath: '/chat/completions',
      responsePath: 'choices.0.message.content',
    },
    {
      id: 'qwen-text',
      name: 'Qwen Text',
      kind: 'qwen',
      role: 'text',
      enabled: true,
      baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      apiKey: '',
      model: 'qwen-plus',
      chatPath: '/chat/completions',
      responsePath: 'choices.0.message.content',
    },
    {
      id: 'custom-text',
      name: 'Custom Text Model',
      kind: 'custom',
      role: 'text',
      enabled: true,
      baseUrl: 'http://127.0.0.1:8001/v1',
      apiKey: '',
      model: 'custom-chat-model',
      chatPath: '/chat/completions',
      responsePath: 'choices.0.message.content',
    },
  ],
}
